package com.ujeat.pojo;

import java.util.Date;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.username
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.money
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.loginDate
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    private Date logindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.exitDate
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    private Date exitdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public Account(Integer id, String username, String password, Double money, Date logindate, Date exitdate) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.money = money;
        this.logindate = logindate;
        this.exitdate = exitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public Account() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.username
     *
     * @return the value of account.username
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.username
     *
     * @param username the value for account.username
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.money
     *
     * @return the value of account.money
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.money
     *
     * @param money the value for account.money
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.loginDate
     *
     * @return the value of account.loginDate
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public Date getLogindate() {
        return logindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.loginDate
     *
     * @param logindate the value for account.loginDate
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public void setLogindate(Date logindate) {
        this.logindate = logindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.exitDate
     *
     * @return the value of account.exitDate
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public Date getExitdate() {
        return exitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.exitDate
     *
     * @param exitdate the value for account.exitDate
     *
     * @mbggenerated Tue May 09 17:25:16 CST 2017
     */
    public void setExitdate(Date exitdate) {
        this.exitdate = exitdate;
    }
}